"""Machine-readable failure database. route_failure.py reads this; the prose mirror is in
references/failure-modes.md. class: design_time | process | mixed | secondary.
route: generating-build123d | slicer_printer | both."""

FAILURES = {
    "warping": {"class": "mixed", "route": "both",
                "signs": "corners lift, gap under base",
                "design_fix": "mouse-ears, round sharp corners, or split the part",
                "process_fix": "raise bed temp, add brim, enclose the printer"},
    "stringing": {"class": "mixed", "route": "both",
                  "signs": "thin hairy strands between features",
                  "design_fix": "add vents to cavities, reduce gappy travel",
                  "process_fix": "tune retraction, dry filament, lower temperature"},
    "layer_shift": {"class": "process", "route": "slicer_printer",
                    "signs": "single abrupt horizontal step at one height",
                    "design_fix": None,
                    "process_fix": "belt tension, tighten pulley grub screw, lower accel, check collisions"},
    "under_extrusion": {"class": "mixed", "route": "both",
                        "signs": "thin or missing strands, visible gap-fill texture",
                        "design_fix": "set wall thickness to a whole multiple of nozzle width",
                        "process_fix": "flow calibration, clear clog, raise temp"},
    "elephant_foot": {"class": "mixed", "route": "both",
                      "signs": "bottom 1-3 layers wider than body, smooth not curling",
                      "design_fix": "chamfer bottom edges 0.4-0.5 mm",
                      "process_fix": "lower first-layer flow, enable elephant-foot compensation"},
    "first_layer_adhesion": {"class": "mixed", "route": "both",
                             "signs": "base detaches or curls early",
                             "design_fix": "add brim/raft, reorient for a larger footprint",
                             "process_fix": "tune Z-offset, clean and level bed, adhesive"},
    "delamination": {"class": "mixed", "route": "both",
                     "signs": "horizontal cracks between layers, often mid-height",
                     "design_fix": "reorient so load is in XY; thicken thin Z webs",
                     "process_fix": "raise temp, reduce cooling, dry filament"},
    "ghosting": {"class": "process", "route": "slicer_printer",
                 "signs": "repeating wave echoes fading from sharp corners",
                 "design_fix": None,
                 "process_fix": "input shaping (ADXL345), lower acceleration, tighten frame"},
    "blobs_zits": {"class": "process", "route": "slicer_printer",
                   "signs": "surface bumps and seam blobs",
                   "design_fix": None,
                   "process_fix": "coasting/wipe, retraction tune, seam alignment"},
    "top_pillowing": {"class": "mixed", "route": "both",
                      "signs": "top-surface depressions following the infill below",
                      "design_fix": "top thickness >= 5x layer height; infill >= 15%",
                      "process_fix": "more cooling, add top layers"},
    "top_gaps": {"class": "mixed", "route": "both",
                 "signs": "holes/gaps in the top surface",
                 "design_fix": "thicker top shell",
                 "process_fix": "raise top layer count / infill density"},
    "clog_heat_creep": {"class": "process", "route": "slicer_printer",
                        "signs": "progressive under-extrusion then stop mid-print",
                        "design_fix": None,
                        "process_fix": "hotend fan, lower ambient, clean or replace nozzle"},
    "support_failure": {"class": "design_time", "route": "generating-build123d",
                        "signs": "supports detach, overhang surface ruined",
                        "design_fix": "reorient; chamfer overhangs; teardrop horizontal holes",
                        "process_fix": "denser support interface (last resort)"},
    "bridging_sag": {"class": "mixed", "route": "both",
                     "signs": "drooping filament across an unsupported span",
                     "design_fix": "shorten span below ~10 mm or add a support rib",
                     "process_fix": "bridge speed/flow, more cooling"},
    "z_seam_zits": {"class": "mixed", "route": "both",
                    "signs": "vertical scar line up one side",
                    "design_fix": "add a sharp vertical edge to host the seam",
                    "process_fix": "align seam to a corner"},
    "spaghetti": {"class": "secondary", "route": "generating-build123d",
                  "signs": "tangled mid-air filament (a downstream symptom)",
                  "design_fix": "diagnose the root failure from what remains on the bed",
                  "process_fix": "fix the root cause (adhesion or layer shift)"},
}
